version: '3'

services:
  mysql_db:
    image: mysql:8
    container_name: mysql_db
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: springstudent
      MYSQL_DATABASE: expense_tracker
      MYSQL_USER: root
      MYSQL_PASSWORD: springstudent
    ports:
      - "6603:3306"

  spring-expense-tracker:
    build: .
    depends_on:
       - mysql_db
    #restart: always
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=springstudent
      - DB_NAME=expense_tracker
    links:
      - mysql_db:mysql
    ports:
      - "7071:7071"
